# Site Settings
title:               CocoaHeadsCZ
tagline:             Prague chapter of CocoaHeads
description:
baseurl:            #"/"
url:                #"https://cocoaheads.cz"
github:
  url:               #"https://github.com/CocoaHeadsCZ/Website"
author:
  name:              "CocoaHeadsCZ"
  email:             "cocoaheadscz@gmail.com"
  twitter:           "cocoaheadscz"
  github:            "cocoaheadscz"
navigation:

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
